export const Icons = {
	"dashboard": "fas fa-fw fa-tachometer-alt",
	"folder": "fas fa-fw fa-folder",
	"toparrow": "fas fa-angle-up",
	"users": "fas fa-users",
	"user": "fas fa-user",
	"company": "fas fa-industry",
	"stagecenter": "fas fa-code-branch",
	"view": "fas fa-eye",
	"edit": "fas fa-edit",
	"delete": "fas fa-trash-alt",
	"plus": "fas fa-plus-square",
	"print": "fas fa-print",
	"table": "fas fa-table",
	"info": "fas fa-poll-h",
	"config": "fas fa-wrench",
	"edituser": "fad fa-user-edit",
	"download": "fas fa-download",
	"loadspin": "fas fa-download",
	"loading": "fas fa-circle-notch fa-spin",
	"regras": "fas fa-table",
	"modulo": "fas fa-download",
	"contato": "fas fa-phone",
	"financeiro": "fas fa-download",
	"apolice": "fas fa-download",
	"vaga": "fas fa-user",
	"encaminhamento": "fas fa-download",
	"atividades": "fas fa-tasks",
	"questionario": "fas fa-question",
	"question": "fas fa-question",
	"city": "fas fa-city",
	"vehicle": "fas fa-car-side",
	"driver": "fas fa-id-card",
	"product": "fas fa-box",
	"casualty": "fas fa-car-crash",
	"trash": "fas fa-trash-alt",
	"appraiser": "fas fa-address-card",
	"allowed_origins": "fas fa-code-branch",
	"emitidas": "fas fa-share",
	"recebidas": "fas fa-undo",
	"inabilitadas": "fas fa-exclamation-triangle",
	"total": "fas fa-tasks",
	"building": "fas fa-building",
	"company_panel": "fas fa-chart-line",
	"xmlUpload": "fas fa-upload",
	"password_hide": "fas fa-eye",
	"cadastro": "fas fa-table",
	"documentos_fiscais": "fas fa-file",
	"sinistros": "fas fa-car-crash",
	"avaliacoes_externas": "fas fa-check",
	"red": "fas fa-thumbs-o-up"

};

